apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: portfolio
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: ag126667/portfolio:2672c5fe23dd074d1d21b39952485eac043922f9
          ports:
            - containerPort: 80
