apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-app
  namespace: portfolio
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
        - name: portfolio
          image: ag126667/portfolio:201b8a9560c87605bb115fbeca389e66d3dc1e8f
          ports:
            - containerPort: 80
