apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: my-team
  namespace: argocd
spec:
  description: Project for my team apps
  sourceRepos:
    - https://github.com/arvindgupta-cloud/deploy-portfolio-using-argocd.git
  destinations:
    - namespace: frontend
      server: '*'  
    - namespace: default
      server: '*'  
    - namespace: portfolio
      server: '*' 
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  roles:
    - name: my-admins
      description: Admins for my team
      policies:
        - p, proj:my-team:my-admins, applications, *, my-team/*, allow
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-my
  namespace: portfolio
spec:
  project: my-team
  source:
    repoURL: https://github.com/arvindgupta-cloud/deploy-portfolio-using-argocd.git
    targetRevision: main
    path: k8s
  destination:
    server: https://136.112.221.25
    namespace: portfolio
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
